### ISSUE TITLE
Why not run into my server?

### ISSUE THREAD

**Issue by Zeokat** [clue/psocksd#28]
I'm trying to run psocksd into my server but i get a fatal error. I'm runing Ubuntu 16.04 with PHP 7.

I just downloaded the latest phar release and executed the file with root rights. How can i solve this?

```
root@pharingphp:~# php psocksd.phar 7777
PHP Fatal error:  Uncaught Error: Call to undefined function Clue\React\Stdio\mb_strwidth() in phar:///root/psocksd.phar/vendor/clue/stdio-react/src/Readline.php:572
Stack trace:
#0 phar:///root/psocksd.phar/vendor/clue/stdio-react/src/Readline.php(371): Clue\React\Stdio\Readline->strwidth('')
#1 phar:///root/psocksd.phar/vendor/clue/stdio-react/src/Readline.php(96): Clue\React\Stdio\Readline->redraw()
#2 phar:///root/psocksd.phar/src/App.php(87): Clue\React\Stdio\Readline->setPrompt('> ')
#3 phar:///root/psocksd.phar/src/App.php(49): Clue\Psocksd\App->start(Array)
#4 [internal function]: Clue\Psocksd\App->Clue\Psocksd\{closure}(Array)
#5 phar:///root/psocksd.phar/vendor/clue/commander/src/Route.php(77): call_user_func(Object(Closure), Array)
#6 phar:///root/psocksd.phar/vendor/clue/commander/src/Router.php(179): Clue\Commander\Route->__invoke(Array)
#7 phar:///root/psocksd.phar/vendor/clue/commander/src/Router.php(152): Clue\Commander\Router->handleArgs(Array)
#8 phar:///root/psocksd.phar/src/App.php(58): Clue\Commander\Route in phar:///root/psocksd.phar/vendor/clue/stdio-react/src/Readline.php on line 572
```

As you can see, i'm runing stock PHP 7 provided on official repos:
```
root@pharingphp:~# php --version
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.15-0ubuntu0.16.04.4, Copyright (c) 1999-2017, by Zend Technologies
```

Thanks in advance for your help.

**Comment by clue** [comment]
Thanks for filing this ticket! This is a known issue due to an undocumented dependency and will likely be resolved in the next version:

```bash
$ sudo apt install php7.0-mbstring

# or for older installations
$ sudo apt-get install php5-mbstring
```

I hope this helps :+1:
